# Generated by Django 3.0.2 on 2020-01-20 20:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0001_initial'),
        ('guatudu', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='business',
            name='admin_profiles',
            field=models.ManyToManyField(to='guatudu.AdminProfile'),
        ),
        migrations.AddField(
            model_name='adminprofile',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Role'),
        ),
        migrations.AddField(
            model_name='adminprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='adminbusiness',
            name='admin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='guatudu.AdminProfile'),
        ),
        migrations.AddField(
            model_name='adminbusiness',
            name='business',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='guatudu.Business'),
        ),
    ]
